//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class agro_mydbEntities : DbContext
    {
        public agro_mydbEntities()
            : base("name=agro_mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ccategory> ccategory { get; set; }
        public virtual DbSet<rbasket> rbasket { get; set; }
        public virtual DbSet<rcontract> rcontract { get; set; }
        public virtual DbSet<rcontractor_info> rcontractor_info { get; set; }
        public virtual DbSet<rnews> rnews { get; set; }
        public virtual DbSet<rorder> rorder { get; set; }
        public virtual DbSet<rstock> rstock { get; set; }
        public virtual DbSet<ruser> ruser { get; set; }
        public virtual DbSet<ruser_info> ruser_info { get; set; }
        public virtual DbSet<scity> scity { get; set; }
        public virtual DbSet<sstreet> sstreet { get; set; }
    }
}
