//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rcontract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rcontract()
        {
            this.rorder = new HashSet<rorder>();
        }
    
        public int PK_ID { get; set; }
        public int FLAG_SIGNATURE { get; set; }
        public int FLAG_PAYMENT { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime DATE_SIGNATURE { get; set; }
        public int IS_ACTIVE { get; set; }
        public int IS_READY { get; set; }
        public int FK_ID_CONTRACT_CONTRACTOR { get; set; }
        public int FK_ID_CONTRACT_USER { get; set; }
    
        public virtual rcontractor_info rcontractor_info { get; set; }
        public virtual ruser_info ruser_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rorder> rorder { get; set; }
    }
}
