//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rnews
    {
        public int PK_ID { get; set; }
        public string NAME { get; set; }
        public string TEXT { get; set; }
        public System.DateTime DATE { get; set; }
        public string IMAGE_PATH { get; set; }
        public int IS_ACTIVE { get; set; }
    }
}
