//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rorder
    {
        public int PK_ID { get; set; }
        public int QANTITY { get; set; }
        public int FK_ID_CONTRACT { get; set; }
        public int FK_ID_STOCK { get; set; }
    
        public virtual rcontract rcontract { get; set; }
        public virtual rstock rstock { get; set; }
    }
}
