//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rstock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rstock()
        {
            this.rbasket = new HashSet<rbasket>();
            this.rorder = new HashSet<rorder>();
        }
    
        public int PK_ID { get; set; }
        public string NAME { get; set; }
        public int QANTITY { get; set; }
        public int STEP { get; set; }
        public decimal PRICE_ONE { get; set; }
        public string INFO { get; set; }
        public string IMAGE_PATH { get; set; }
        public int IS_ACTIVE { get; set; }
        public int FK_ID_CATEGORY { get; set; }
        public System.DateTime DATE_ADDED { get; set; }
    
        public virtual ccategory ccategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rbasket> rbasket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rorder> rorder { get; set; }
    }
}
