//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ruser()
        {
            this.rbasket = new HashSet<rbasket>();
            this.rcontractor_info = new HashSet<rcontractor_info>();
            this.ruser_info = new HashSet<ruser_info>();
        }
    
        public int PK_ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string NAME_COMPANY { get; set; }
        public string LEGAL_ADDRESS { get; set; }
        public string MAIL_ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public int INN { get; set; }
        public int KPP { get; set; }
        public int CHECKING_ACCOUNT { get; set; }
        public string BANK { get; set; }
        public int CORRESPONDENT_ACCOUNT { get; set; }
        public int BIK { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public int FK_ID_STREET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rbasket> rbasket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rcontractor_info> rcontractor_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ruser_info> ruser_info { get; set; }
        public virtual sstreet sstreet { get; set; }
    }
}
